const INITIAL_TEMPLATES = [
  {
    title: "Node.js Express Microservice",
    description:
      "A lightweight REST API starter with TypeScript and Docker support.",
    categoryName: "Application/Project Root",
    yaml: "apiVersion: v1\nkind: Template\nmetadata:\n  name: node-express-v1",
  },
  {
    title: "React Dashboard Component",
    description: "Scaffolds a standard React component with Shadcn UI imports.",
    categoryName: "Component/Feature Structure",
    yaml: "apiVersion: v1\nkind: Template\nmetadata:\n  name: react-component",
  },
];

const CATEGORIES = [
  {
    name: "Application/Project Root",
  },
  { name: "Component/Feature Structure" },
  { name: "Configuration & Build Tools" },
];

const WIZARD_CATALOG_CATEGORIES = [
  {
    id: "web",
    label: "Web Application",
    description: "Full-stack or frontend frameworks",
    icon: "Globe",
    accentClass: "border-blue-400 bg-blue-50",
    displayOrder: 1,
  },
  {
    id: "mobile",
    label: "Mobile App",
    description: "Native or cross-platform mobile stacks",
    icon: "Smartphone",
    accentClass: "border-violet-400 bg-violet-50",
    displayOrder: 2,
  },
  {
    id: "backend",
    label: "Backend / API",
    description: "REST APIs and backend service frameworks",
    icon: "Server",
    accentClass: "border-emerald-400 bg-emerald-50",
    displayOrder: 3,
  },
  {
    id: "data",
    label: "Data & AI",
    description: "ML, data processing, and notebook templates",
    icon: "BrainCircuit",
    accentClass: "border-amber-400 bg-amber-50",
    displayOrder: 4,
  },
  {
    id: "devops",
    label: "DevOps / Infrastructure",
    description: "IaC, pipelines, and platform operations",
    icon: "Network",
    accentClass: "border-orange-400 bg-orange-50",
    displayOrder: 5,
  },
] as const;

const WIZARD_FRAMEWORKS = [
  {
    id: "nextjs",
    categoryId: "web",
    label: "Next.js",
    description: "React full-stack framework with SSR/SSG",
    badge: "JS/TS",
    popularity: "popular",
    tags: ["React", "SSR", "App Router"],
    displayOrder: 1,
  },
  {
    id: "react-vite",
    categoryId: "web",
    label: "React + Vite",
    description: "Fast SPA with Vite and optional TypeScript",
    badge: "JS/TS",
    popularity: "trending",
    tags: ["React", "Vite", "SPA"],
    displayOrder: 2,
  },
  {
    id: "vue-nuxt",
    categoryId: "web",
    label: "Vue + Nuxt",
    description: "Vue SSR/SSG with Nuxt",
    badge: "Vue",
    tags: ["Vue", "Nuxt", "SSR"],
    displayOrder: 3,
  },
  {
    id: "sveltekit",
    categoryId: "web",
    label: "SvelteKit",
    description: "Compiler-first framework with file routing",
    badge: "Svelte",
    tags: ["Svelte", "Routing"],
    displayOrder: 4,
  },
  {
    id: "laravel",
    categoryId: "web",
    label: "Laravel",
    description: "PHP framework with Eloquent and Artisan",
    badge: "PHP",
    tags: ["PHP", "MVC"],
    displayOrder: 5,
  },
  {
    id: "django",
    categoryId: "web",
    label: "Django",
    description: "Python framework with admin and ORM",
    badge: "Python",
    tags: ["Python", "ORM"],
    displayOrder: 6,
  },
  {
    id: "rails",
    categoryId: "web",
    label: "Ruby on Rails",
    description: "Convention-over-configuration Ruby framework",
    badge: "Ruby",
    popularity: "enterprise",
    tags: ["Ruby", "MVC"],
    displayOrder: 7,
  },

  {
    id: "expo",
    categoryId: "mobile",
    label: "React Native + Expo",
    description: "Cross-platform mobile with Expo workflow",
    badge: "JS/TS",
    popularity: "popular",
    tags: ["React Native", "iOS", "Android"],
    displayOrder: 1,
  },
  {
    id: "flutter",
    categoryId: "mobile",
    label: "Flutter",
    description: "Cross-platform mobile toolkit",
    badge: "Dart",
    popularity: "popular",
    tags: ["Flutter", "iOS", "Android"],
    displayOrder: 2,
  },
  {
    id: "swift-ios",
    categoryId: "mobile",
    label: "Swift (iOS)",
    description: "Native iOS app architecture",
    badge: "Swift",
    tags: ["SwiftUI", "MVVM"],
    displayOrder: 3,
  },
  {
    id: "kotlin-android",
    categoryId: "mobile",
    label: "Kotlin (Android)",
    description: "Native Android with Compose",
    badge: "Kotlin",
    tags: ["Compose", "Android"],
    displayOrder: 4,
  },

  {
    id: "express",
    categoryId: "backend",
    label: "Express.js",
    description: "Lightweight Node.js REST API",
    badge: "Node",
    popularity: "popular",
    tags: ["Node", "REST"],
    displayOrder: 1,
  },
  {
    id: "nestjs",
    categoryId: "backend",
    label: "NestJS",
    description: "TypeScript backend framework with DI",
    badge: "Node/TS",
    popularity: "enterprise",
    tags: ["TypeScript", "DI"],
    displayOrder: 2,
  },
  {
    id: "fastapi",
    categoryId: "backend",
    label: "FastAPI",
    description: "Async Python API with OpenAPI",
    badge: "Python",
    popularity: "trending",
    tags: ["Python", "Async"],
    displayOrder: 3,
  },
  {
    id: "go-gin",
    categoryId: "backend",
    label: "Go + Gin",
    description: "Fast Go API framework",
    badge: "Go",
    tags: ["Go", "REST"],
    displayOrder: 4,
  },
  {
    id: "spring-boot",
    categoryId: "backend",
    label: "Spring Boot",
    description: "Enterprise Java API framework",
    badge: "Java",
    popularity: "enterprise",
    tags: ["Java", "Spring"],
    displayOrder: 5,
  },

  {
    id: "pytorch",
    categoryId: "data",
    label: "PyTorch",
    description: "Deep learning training templates",
    badge: "Python",
    tags: ["ML", "Training"],
    displayOrder: 1,
  },
  {
    id: "langchain",
    categoryId: "data",
    label: "LangChain",
    description: "LLM application and agent templates",
    badge: "Python",
    tags: ["LLM", "Agents"],
    displayOrder: 2,
  },
  {
    id: "data-pipeline",
    categoryId: "data",
    label: "Data Pipeline",
    description: "ETL/data engineering templates",
    badge: "Python",
    tags: ["ETL", "DBT"],
    displayOrder: 3,
  },
  {
    id: "jupyter",
    categoryId: "data",
    label: "Jupyter",
    description: "Notebook-based data science workspace",
    badge: "Notebook",
    tags: ["Notebooks", "Analysis"],
    displayOrder: 4,
  },

  {
    id: "docker-compose",
    categoryId: "devops",
    label: "Docker Compose",
    description: "Local multi-service orchestration",
    badge: "Docker",
    tags: ["Containers", "Compose"],
    displayOrder: 1,
  },
  {
    id: "github-actions",
    categoryId: "devops",
    label: "GitHub Actions",
    description: "CI/CD automation templates",
    badge: "CI/CD",
    tags: ["Pipelines", "Automation"],
    displayOrder: 2,
  },
  {
    id: "terraform-aws",
    categoryId: "devops",
    label: "Terraform AWS",
    description: "AWS infrastructure as code",
    badge: "Terraform",
    tags: ["IaC", "AWS"],
    displayOrder: 3,
  },
  {
    id: "kubernetes",
    categoryId: "devops",
    label: "Kubernetes",
    description: "K8s deployment and operations templates",
    badge: "K8s",
    tags: ["Kubernetes", "Ops"],
    displayOrder: 4,
  },
] as const;

const WIZARD_OPTIONS = [
  {
    id: "typescript",
    label: "TypeScript",
    description: "Enable strict TypeScript setup",
    tier: "QUALITY",
    displayOrder: 1,
  },
  {
    id: "tailwind",
    label: "Tailwind CSS",
    description: "Include Tailwind setup",
    tier: "FEATURES",
    displayOrder: 2,
  },
  {
    id: "prisma",
    label: "Prisma",
    description: "Add Prisma ORM integration",
    tier: "FEATURES",
    displayOrder: 3,
  },
  {
    id: "auth",
    label: "Authentication",
    description: "Add authentication scaffolding",
    tier: "SECURITY",
    displayOrder: 4,
  },
  {
    id: "docker",
    label: "Docker",
    description: "Add containerization files",
    tier: "INFRASTRUCTURE",
    displayOrder: 5,
  },
  {
    id: "ci",
    label: "CI Pipeline",
    description: "Add CI workflow templates",
    tier: "QUALITY",
    displayOrder: 6,
  },
  {
    id: "mysql",
    label: "MySQL",
    description: "Configure MySQL data store",
    tier: "FEATURES",
    displayOrder: 7,
  },
  {
    id: "redis",
    label: "Redis",
    description: "Configure Redis cache/queue",
    tier: "FEATURES",
    displayOrder: 8,
  },
  {
    id: "jwt",
    label: "JWT",
    description: "JWT-based auth flow",
    tier: "SECURITY",
    displayOrder: 9,
  },
  {
    id: "swagger",
    label: "Swagger/OpenAPI",
    description: "API docs scaffolding",
    tier: "QUALITY",
    displayOrder: 10,
  },
  {
    id: "drf",
    label: "Django REST Framework",
    description: "Enable DRF boilerplate",
    tier: "FEATURES",
    displayOrder: 11,
  },
  {
    id: "celery",
    label: "Celery",
    description: "Background worker setup",
    tier: "INFRASTRUCTURE",
    displayOrder: 12,
  },
  {
    id: "devise",
    label: "Devise",
    description: "Rails authentication with Devise",
    tier: "SECURITY",
    displayOrder: 13,
  },
  {
    id: "rspec",
    label: "RSpec",
    description: "Rails testing setup",
    tier: "QUALITY",
    displayOrder: 14,
  },
  {
    id: "firebase",
    label: "Firebase",
    description: "Firebase integration",
    tier: "FEATURES",
    displayOrder: 15,
  },
  {
    id: "helm",
    label: "Helm",
    description: "Helm chart support",
    tier: "INFRASTRUCTURE",
    displayOrder: 16,
  },
  {
    id: "monitoring",
    label: "Monitoring",
    description: "Observability setup",
    tier: "QUALITY",
    displayOrder: 17,
  },
  {
    id: "codeql",
    label: "CodeQL",
    description: "Security scanning workflow",
    tier: "SECURITY",
    displayOrder: 18,
  },
  {
    id: "terraform",
    label: "Terraform",
    description: "IaC workflow integration",
    tier: "INFRASTRUCTURE",
    displayOrder: 19,
  },
] as const;

const FRAMEWORK_OPTION_MAP: Record<string, string[]> = {
  nextjs: ["typescript", "tailwind", "prisma", "auth", "docker", "ci"],
  "react-vite": ["typescript", "tailwind", "docker", "ci"],
  "vue-nuxt": ["typescript", "tailwind", "docker", "ci"],
  sveltekit: ["typescript", "tailwind", "prisma", "docker", "ci"],
  laravel: ["mysql", "redis", "docker", "ci"],
  django: ["drf", "celery", "docker", "ci"],
  rails: ["devise", "rspec", "docker", "ci"],

  expo: ["typescript", "firebase", "ci"],
  flutter: ["firebase", "ci"],
  "swift-ios": ["ci"],
  "kotlin-android": ["firebase", "ci"],

  express: ["typescript", "prisma", "jwt", "docker", "ci"],
  nestjs: ["typescript", "prisma", "jwt", "swagger", "docker", "ci"],
  fastapi: ["auth", "celery", "docker", "ci"],
  "go-gin": ["jwt", "swagger", "docker", "ci"],
  "spring-boot": ["jwt", "swagger", "docker", "ci"],

  pytorch: ["docker", "ci"],
  langchain: ["auth", "docker", "ci"],
  "data-pipeline": ["docker", "ci", "terraform"],
  jupyter: ["docker", "ci"],

  "docker-compose": ["docker", "monitoring", "ci"],
  "github-actions": ["ci", "codeql", "terraform"],
  "terraform-aws": ["terraform", "monitoring", "ci"],
  kubernetes: ["helm", "monitoring", "ci"],
};

export {
  INITIAL_TEMPLATES,
  CATEGORIES,
  WIZARD_CATALOG_CATEGORIES,
  WIZARD_FRAMEWORKS,
  WIZARD_OPTIONS,
  FRAMEWORK_OPTION_MAP,
};
