import { toYaml, type ScaffoldFile } from "./shared.js";

export function buildExpressYamlModular(opts: Set<string>): string {
  const ts = opts.has("typescript");
  const ext = ts ? "ts" : "js";
  const files: ScaffoldFile[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "1.0.0",
  "main": "${ts ? "dist/index.js" : "src/index.js"}",
  "scripts": {
    "dev": "${ts ? "ts-node src/index.ts" : "node src/index.js"}",
    "build": "${ts ? "tsc" : "echo 'No build step'"}",
    "test": "jest"
  },
  "dependencies": {
    "express": "^4.19.2"${opts.has("prisma") ? `,\n    "@prisma/client": "^5.0.0"` : ""}${opts.has("jwt") ? `,\n    "jsonwebtoken": "^9.0.0",\n    "bcrypt": "^5.1.1"` : ""}
  }${ts ? `,\n  "devDependencies": {\n    "typescript": "^5",\n    "ts-node": "^10",\n    "@types/express": "^4",\n    "@types/node": "^20"\n  }` : ""}
}
`,
    },
    {
      path: `src/index.${ext}`,
      content: `import express from "express";

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get("/health", (_req, res) => {
  res.json({ status: "ok", service: "{{projectName}}" });
});

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});

export default app;
`,
    },
    {
      path: ".env.example",
      content: `PORT=3000
NODE_ENV=development${opts.has("prisma") ? `\nDATABASE_URL=postgresql://user:password@localhost:5432/{{projectName}}` : ""}${opts.has("jwt") ? `\nJWT_SECRET=your-secret-key-here` : ""}
`,
    },
  ];

  if (ts) {
    files.push({
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
`,
    });
  }

  if (opts.has("prisma")) {
    files.push({
      path: "prisma/schema.prisma",
      content: `datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`,
    });
  }

  if (opts.has("docker")) {
    files.push({
      path: "Dockerfile",
      content: `FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

${ts ? `FROM base AS builder\nRUN npm ci\nCOPY . .\nRUN npm run build\n\nFROM node:20-alpine AS runner\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY --from=base /app/node_modules ./node_modules\n` : "COPY . .\n"}EXPOSE 3000
CMD ["${ts ? "node dist/index.js" : "node src/index.js"}"]
`,
    });
  }

  if (opts.has("ci")) {
    files.push({
      path: ".github/workflows/ci.yml",
      content: `name: Express CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm test
`,
    });
  }

  files.push({
    path: "README.md",
    content: `# {{projectName}}

Generated by DevCentral Scaffolder.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Endpoints

- \`GET /health\` — Health check
`,
  });

  return toYaml(files);
}

export function buildNestJsYamlModular(opts: Set<string>): string {
  const files: ScaffoldFile[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.0.1",
  "scripts": {
    "build": "nest build",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:prod": "node dist/main",
    "test": "jest",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"${opts.has("prisma") ? `,\n    "@prisma/client": "^5.0.0"` : ""}${opts.has("jwt") ? `,\n    "@nestjs/jwt": "^10.1.1",\n    "@nestjs/passport": "^10.0.0",\n    "passport": "^0.6.0",\n    "passport-jwt": "^4.0.1"` : ""}
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "typescript": "^5",
    "@types/express": "^4.17.21",
    "@types/node": "^20"
  }
}
`,
    },
    {
      path: "src/main.ts",
      content: `import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module";

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(process.env.PORT || 3000);
}
bootstrap();
`,
    },
    {
      path: "src/app.module.ts",
      content: `import { Module } from "@nestjs/common";
import { AppController } from "./app.controller";
import { AppService } from "./app.service";

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
`,
    },
    {
      path: "src/app.controller.ts",
      content: `import { Controller, Get } from "@nestjs/common";
import { AppService } from "./app.service";

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }

  @Get("health")
  getHealth() {
    return { status: "ok", service: "{{projectName}}" };
  }
}
`,
    },
    {
      path: "src/app.service.ts",
      content: `import { Injectable } from "@nestjs/common";

@Injectable()
export class AppService {
  getHello(): string {
    return "Welcome to {{projectName}}!";
  }
}
`,
    },
    {
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false
  }
}
`,
    },
  ];

  if (opts.has("prisma")) {
    files.push({
      path: "prisma/schema.prisma",
      content: `datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
}
`,
    });
  }

  if (opts.has("docker")) {
    files.push({
      path: "Dockerfile",
      content: `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000
CMD ["node", "dist/main"]
`,
    });
  }

  files.push({
    path: "README.md",
    content: `# {{projectName}}

Generated by DevCentral Scaffolder.

## Getting Started

\`\`\`bash
npm install
npm run start:dev
\`\`\`
`,
  });

  return toYaml(files);
}

export function buildFastApiYamlModular(opts: Set<string>): string {
  const files: ScaffoldFile[] = [
    {
      path: "requirements.txt",
      content: `fastapi>=0.109.0
uvicorn[standard]>=0.27.0
pydantic>=2.5.0${opts.has("postgres") ? `\nasyncpg>=0.29.0\nsqlalchemy[asyncio]>=2.0.0\nalembic>=1.13.0` : ""}${opts.has("jwt") ? `\npython-jose[cryptography]>=3.3.0\npasslib[bcrypt]>=1.7.4` : ""}${opts.has("celery") ? `\ncelery>=5.3.0\nredis>=5.0.0` : ""}
`,
    },
    {
      path: "app/main.py",
      content: `from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{{projectName}}",
    description="Generated by DevCentral Scaffolder",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
async def health_check():
    return {"status": "ok", "service": "{{projectName}}"}


@app.get("/")
async def root():
    return {"message": "Welcome to {{projectName}}"}
`,
    },
    {
      path: ".env.example",
      content: `APP_ENV=development${opts.has("postgres") ? `\nDATABASE_URL=postgresql+asyncpg://user:password@localhost:5432/{{projectName}}` : ""}${opts.has("jwt") ? `\nSECRET_KEY=your-secret-key-here\nALGORITHM=HS256\nACCESS_TOKEN_EXPIRE_MINUTES=30` : ""}
`,
    },
  ];

  if (opts.has("docker")) {
    files.push({
      path: "Dockerfile",
      content: `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
`,
    });
  }

  if (opts.has("ci")) {
    files.push({
      path: ".github/workflows/ci.yml",
      content: `name: FastAPI CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt pytest httpx
      - run: pytest
`,
    });
  }

  files.push({
    path: "README.md",
    content: `# {{projectName}}

Generated by DevCentral Scaffolder.

## Getting Started

\`\`\`bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
uvicorn app.main:app --reload
\`\`\`

Docs available at http://localhost:8000/docs
`,
  });

  return toYaml(files);
}

export function buildGoGinYamlModular(opts: Set<string>): string {
  const files: ScaffoldFile[] = [
    {
      path: "go.mod",
      content: `module github.com/{{projectName}}

go 1.22

require (
\tgithub.com/gin-gonic/gin v1.9.1${opts.has("gorm") ? `\n\tgorm.io/gorm v1.25.7\n\tgorm.io/driver/postgres v1.5.6` : ""}${opts.has("jwt") ? `\n\tgithub.com/golang-jwt/jwt/v5 v5.2.0` : ""}
)
`,
    },
    {
      path: "main.go",
      content: `package main

import (
\t"net/http"

\t"github.com/gin-gonic/gin"
)

func main() {
\tr := gin.Default()

\tr.GET("/health", func(c *gin.Context) {
\t\tc.JSON(http.StatusOK, gin.H{"status": "ok", "service": "{{projectName}}"})
\t})

\tr.GET("/", func(c *gin.Context) {
\t\tc.JSON(http.StatusOK, gin.H{"message": "Welcome to {{projectName}}"})
\t})

\tr.Run(":8080")
}
`,
    },
    {
      path: ".env.example",
      content: `PORT=8080
GIN_MODE=debug${opts.has("gorm") ? `\nDATABASE_URL=postgresql://user:password@localhost:5432/{{projectName}}?sslmode=disable` : ""}${opts.has("jwt") ? `\nJWT_SECRET=your-secret-key-here` : ""}
`,
    },
  ];

  if (opts.has("docker")) {
    files.push({
      path: "Dockerfile",
      content: `FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]
`,
    });
  }

  if (opts.has("ci")) {
    files.push({
      path: ".github/workflows/ci.yml",
      content: `name: Go Gin CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go mod download
      - run: go build ./...
      - run: go test ./...
`,
    });
  }

  files.push({
    path: "README.md",
    content: `# {{projectName}}

Generated by DevCentral Scaffolder.

## Getting Started

\`\`\`bash
go mod tidy
go run main.go
\`\`\`
`,
  });

  return toYaml(files);
}

export function buildSpringBootYamlModular(opts: Set<string>): string {
  const files: ScaffoldFile[] = [
    {
      path: "pom.xml",
      content: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.2</version>
  </parent>
  <groupId>com.{{projectName}}</groupId>
  <artifactId>{{projectName}}</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
    <java.version>21</java.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>${opts.has("jpa") ? `\n    <dependency>\n      <groupId>org.springframework.boot</groupId>\n      <artifactId>spring-boot-starter-data-jpa</artifactId>\n    </dependency>` : ""}${opts.has("postgres") ? `\n    <dependency>\n      <groupId>org.postgresql</groupId>\n      <artifactId>postgresql</artifactId>\n    </dependency>` : ""}${opts.has("security") ? `\n    <dependency>\n      <groupId>org.springframework.boot</groupId>\n      <artifactId>spring-boot-starter-security</artifactId>\n    </dependency>` : ""}
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
`,
    },
    {
      path: "src/main/java/com/{{projectName}}/Application.java",
      content: `package com.{{projectName}};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
`,
    },
    {
      path: "src/main/java/com/{{projectName}}/HealthController.java",
      content: `package com.{{projectName}};

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import java.util.Map;

@RestController
public class HealthController {

    @GetMapping("/health")
    public Map<String, String> health() {
        return Map.of("status", "ok", "service", "{{projectName}}");
    }
}
`,
    },
    {
      path: "src/main/resources/application.properties",
      content: `server.port=8080
spring.application.name={{projectName}}${opts.has("postgres") ? `\nspring.datasource.url=jdbc:postgresql://localhost:5432/{{projectName}}\nspring.datasource.username=postgres\nspring.datasource.password=postgres\nspring.jpa.hibernate.ddl-auto=update` : ""}
`,
    },
  ];

  if (opts.has("docker")) {
    files.push({
      path: "Dockerfile",
      content: `FROM eclipse-temurin:21-jdk AS builder
WORKDIR /app
COPY . .
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
`,
    });
  }

  if (opts.has("ci")) {
    files.push({
      path: ".github/workflows/ci.yml",
      content: `name: Spring Boot CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - run: ./mvnw clean verify
`,
    });
  }

  files.push({
    path: "README.md",
    content: `# {{projectName}}

Generated by DevCentral Scaffolder.

## Getting Started

\`\`\`bash
./mvnw spring-boot:run
\`\`\`
`,
  });

  return toYaml(files);
}
