import { toYaml, type ScaffoldFile } from "./shared.js";

export function buildNextjsYamlModular(opts: Set<string>): string {
  const ts = opts.has("typescript");
  const ext = ts ? "tsx" : "jsx";
  const files: ScaffoldFile[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.0",
    "react": "^18",
    "react-dom": "^18"
  }${
    ts
      ? `,
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18"
  }`
      : ""
  }
}
`,
    },
    {
      path: `src/app/page.${ext}`,
      content: `export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-3xl font-bold">Welcome to {{projectName}}</h1>
    </main>
  );
}
`,
    },
    {
      path: `src/app/layout.${ext}`,
      content: `import type { Metadata } from "next";${opts.has("tailwind") ? `\nimport "./globals.css";` : ""}

export const metadata: Metadata = {
  title: "{{projectName}}",
  description: "Generated by DevCentral Scaffolder",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    },
  ];

  if (ts) {
    files.push({
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`,
    });
  }

  if (opts.has("tailwind")) {
    files.push({
      path: "tailwind.config.ts",
      content: `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: { extend: {} },
  plugins: [],
};
export default config;
`,
    });
    files.push({
      path: "src/app/globals.css",
      content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`,
    });
  }

  if (opts.has("prisma")) {
    files.push({
      path: "prisma/schema.prisma",
      content: `datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`,
    });
  }

  if (opts.has("auth")) {
    files.push({
      path: `src/app/api/auth/[...nextauth]/route.${ts ? "ts" : "js"}`,
      content: `import NextAuth from "next-auth";
import GithubProvider from "next-auth/providers/github";

const handler = NextAuth({
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID!,
      clientSecret: process.env.GITHUB_SECRET!,
    }),
  ],
});

export { handler as GET, handler as POST };
`,
    });
  }

  if (opts.has("docker")) {
    files.push({
      path: "Dockerfile",
      content: `FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM base AS builder
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
`,
    });
  }

  if (opts.has("ci")) {
    files.push({
      path: ".github/workflows/ci.yml",
      content: `name: Next.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run lint
`,
    });
  }

  files.push({
    path: "README.md",
    content: `# {{projectName}}

Generated by DevCentral Scaffolder.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`
`,
  });

  return toYaml(files);
}

export function buildReactViteYamlModular(opts: Set<string>): string {
  const ts = opts.has("typescript");
  const ext = ts ? "tsx" : "jsx";
  const files: ScaffoldFile[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"${ts ? `,\n    "typecheck": "tsc --noEmit"` : ""}
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "vite": "^5.0.0",
    "@vitejs/plugin-react": "^4.0.0"${ts ? `,\n    "typescript": "^5",\n    "@types/react": "^18",\n    "@types/react-dom": "^18"` : ""}
  }
}
`,
    },
    {
      path: `src/App.${ext}`,
      content: `function App() {
  return (
    <div className="app">
      <h1>Welcome to {{projectName}}</h1>
    </div>
  );
}

export default App;
`,
    },
    {
      path: `src/main.${ext}`,
      content: `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";${opts.has("tailwind") ? `\nimport "./index.css";` : ""}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`,
    },
    {
      path: "index.html",
      content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{projectName}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.${ext}"></script>
  </body>
</html>
`,
    },
  ];

  if (ts) {
    files.push({
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
`,
    });
  }

  if (opts.has("tailwind")) {
    files.push({
      path: "src/index.css",
      content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`,
    });
    files.push({
      path: "tailwind.config.js",
      content: `export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
`,
    });
  }

  if (opts.has("vitest")) {
    files.push({
      path: `src/App.test.${ext}`,
      content: `import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import App from "./App";

describe("App", () => {
  it("renders headline", () => {
    render(<App />);
    expect(screen.getByText(/{{projectName}}/i)).toBeDefined();
  });
});
`,
    });
  }

  files.push({
    path: "README.md",
    content: `# {{projectName}}

Generated by DevCentral Scaffolder.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`
`,
  });

  return toYaml(files);
}
