// ──────────────────────────────────────────────────────────────────────────────
// Wizard YAML Generator — server-side
// All YAML template generation logic lives here; triggered via
//   POST /api/wizard/generate  { frameworkId, optionIds }
// ──────────────────────────────────────────────────────────────────────────────

function toYaml(files: { path: string; content: string }[]): string {
  const lines = ["files:"];
  for (const file of files) {
    lines.push(`  - path: ${file.path}`, "    content: |");
    for (const line of file.content.split("\n")) {
      lines.push(`      ${line}`);
    }
  }
  return lines.join("\n");
}

// ── WEB ───────────────────────────────────────────────────────────────────────

function buildNextjsYaml(opts: Set<string>): string {
  const ts = opts.has("typescript");
  const ext = ts ? "tsx" : "jsx";
  const files: { path: string; content: string }[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.0",
    "react": "^18",
    "react-dom": "^18"
  }${ts ? `,
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18"
  }` : ""}
}
`,
    },
    {
      path: `src/app/page.${ext}`,
      content: `export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-3xl font-bold">Welcome to {{projectName}}</h1>
    </main>
  );
}
`,
    },
    {
      path: `src/app/layout.${ext}`,
      content: `import type { Metadata } from "next";${opts.has("tailwind") ? `\nimport "./globals.css";` : ""}

export const metadata: Metadata = {
  title: "{{projectName}}",
  description: "Generated by DevCentral Scaffolder",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    },
  ];

  if (ts) {
    files.push({
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`,
    });
  }

  if (opts.has("tailwind")) {
    files.push({
      path: "tailwind.config.ts",
      content: `import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: { extend: {} },
  plugins: [],
};
export default config;
`,
    });
    files.push({
      path: "src/app/globals.css",
      content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`,
    });
  }

  if (opts.has("prisma")) {
    files.push({
      path: "prisma/schema.prisma",
      content: `datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
generator client {
  provider = "prisma-client-js"
}
model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`,
    });
  }

  if (opts.has("auth")) {
    files.push({
      path: `src/app/api/auth/[...nextauth]/route.${ts ? "ts" : "js"}`,
      content: `import NextAuth from "next-auth";
import GithubProvider from "next-auth/providers/github";
const handler = NextAuth({
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID!,
      clientSecret: process.env.GITHUB_SECRET!,
    }),
  ],
});
export { handler as GET, handler as POST };
`,
    });
  }

  if (opts.has("docker")) {
    files.push({
      path: "Dockerfile",
      content: `FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm ci
FROM base AS builder
COPY . .
RUN npm run build
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
`,
    });
  }

  if (opts.has("ci")) {
    files.push({
      path: ".github/workflows/ci.yml",
      content: `name: Next.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run lint
`,
    });
  }

  files.push({
    path: "README.md",
    content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
  });

  return toYaml(files);
}

function buildReactViteYaml(opts: Set<string>): string {
  const ts = opts.has("typescript");
  const ext = ts ? "tsx" : "jsx";
  const files: { path: string; content: string }[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"${ts ? `,\n    "typecheck": "tsc --noEmit"` : ""}
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "vite": "^5.0.0",
    "@vitejs/plugin-react": "^4.0.0"${ts ? `,\n    "typescript": "^5",\n    "@types/react": "^18",\n    "@types/react-dom": "^18"` : ""}
  }
}
`,
    },
    {
      path: `src/App.${ext}`,
      content: `function App() {
  return (
    <div>
      <h1>Welcome to {{projectName}}</h1>
    </div>
  );
}
export default App;
`,
    },
    {
      path: `src/main.${ext}`,
      content: `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";${opts.has("tailwind") ? `\nimport "./index.css";` : ""}
ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode><App /></React.StrictMode>
);
`,
    },
    {
      path: "index.html",
      content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{projectName}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.${ext}"></script>
  </body>
</html>
`,
    },
  ];

  if (ts) {
    files.push({
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true
  },
  "include": ["src"]
}
`,
    });
  }

  if (opts.has("tailwind")) {
    files.push({ path: "src/index.css", content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n` });
    files.push({
      path: "tailwind.config.js",
      content: `export default {\n  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],\n  theme: { extend: {} },\n  plugins: [],\n};\n`,
    });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n` });
  return toYaml(files);
}

function buildVueNuxtYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.1.0",
  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "dependencies": {
    "nuxt": "^3.10.0",
    "vue": "^3.4.0"
  }
}
`,
    },
    {
      path: "nuxt.config.ts",
      content: `export default defineNuxtConfig({\n  devtools: { enabled: true },${opts.has("tailwind") ? `\n  modules: ["@nuxtjs/tailwindcss"],` : ""}\n});\n`,
    },
    { path: "pages/index.vue", content: `<template>\n  <div class="container mx-auto p-8">\n    <h1 class="text-3xl font-bold">Welcome to {{projectName}}</h1>\n  </div>\n</template>\n` },
    { path: "app.vue", content: `<template>\n  <NuxtPage />\n</template>\n` },
  ];

  if (opts.has("tailwind")) {
    files.push({ path: "tailwind.config.js", content: `module.exports = {\n  content: ["./components/**/*.{js,vue,ts}", "./layouts/**/*.vue", "./pages/**/*.vue", "./app.vue"],\n  theme: { extend: {} },\n  plugins: [],\n};\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n` });
  return toYaml(files);
}

function buildSvelteKitYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.0.1",
  "type": "module",
  "scripts": { "dev": "vite dev", "build": "vite build", "preview": "vite preview" },
  "dependencies": {
    "@sveltejs/kit": "^2.0.0",
    "svelte": "^4.0.0",
    "vite": "^5.0.0",
    "@sveltejs/adapter-auto": "^3.0.0"
  }
}
`,
    },
    { path: "svelte.config.js", content: `import adapter from "@sveltejs/adapter-auto";\nconst config = { kit: { adapter: adapter() } };\nexport default config;\n` },
    { path: "src/routes/+page.svelte", content: `<h1>Welcome to {{projectName}}</h1>\n<p>A SvelteKit application generated by DevCentral Scaffolder.</p>\n` },
    {
      path: "src/app.html",
      content: `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta name="viewport" content="width=device-width" />\n    %sveltekit.head%\n  </head>\n  <body data-sveltekit-preload-data="hover">\n    <div style="display: contents">%sveltekit.body%</div>\n  </body>\n</html>\n`,
    },
  ];

  if (opts.has("tailwind")) {
    files.push({ path: "src/app.css", content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n` });
    files.push({ path: "tailwind.config.js", content: `export default {\n  content: ["./src/**/*.{html,js,svelte,ts}"],\n  theme: { extend: {} },\n  plugins: [],\n};\n` });
  }

  if (opts.has("prisma")) {
    files.push({
      path: "prisma/schema.prisma",
      content: `datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\ngenerator client {\n  provider = "prisma-client-js"\n}\nmodel User {\n  id        String   @id @default(cuid())\n  email     String   @unique\n  createdAt DateTime @default(now())\n}\n`,
    });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n` });
  return toYaml(files);
}

function buildLaravelYaml(opts: Set<string>): string {
  let compose = `services:\n  app:\n    build: .\n    ports:\n      - "8000:8000"\n    env_file: .env\n    depends_on:`;
  if (opts.has("mysql")) compose += `\n      - db`;
  if (opts.has("redis")) compose += `\n      - redis`;
  if (opts.has("mysql")) {
    compose += `\n\n  db:\n    image: mysql:8\n    environment:\n      MYSQL_ROOT_PASSWORD: secret\n      MYSQL_DATABASE: app\n    ports:\n      - "3306:3306"\n    healthcheck:\n      test: ["CMD", "mysqladmin", "ping"]\n      interval: 10s\n      retries: 5`;
  }
  if (opts.has("redis")) {
    compose += `\n\n  redis:\n    image: redis:7-alpine\n    ports:\n      - "6379:6379"`;
  }

  let env = `APP_NAME={{projectName}}\nAPP_ENV=local\nAPP_KEY=\nAPP_DEBUG=true\nAPP_URL=http://localhost\n`;
  if (opts.has("mysql")) env += `\nDB_CONNECTION=mysql\nDB_HOST=db\nDB_PORT=3306\nDB_DATABASE=app\nDB_USERNAME=root\nDB_PASSWORD=secret\n`;
  if (opts.has("redis")) env += `\nCACHE_DRIVER=redis\nREDIS_HOST=redis\nREDIS_PORT=6379\n`;

  const files: { path: string; content: string }[] = [
    { path: "docker-compose.yml", content: compose },
    { path: ".env.example", content: env },
  ];

  if (opts.has("ci")) {
    files.push({
      path: ".github/workflows/ci.yml",
      content: `name: Laravel CI\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: shivammathur/setup-php@v2\n        with:\n          php-version: "8.3"\n      - run: composer install --no-interaction --prefer-dist\n      - run: php artisan test\n`,
    });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\ncp .env.example .env\ndocker compose up -d\ndocker compose exec app composer install\ndocker compose exec app php artisan key:generate\n\`\`\`\n` });
  return toYaml(files);
}

function buildDjangoYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "requirements.txt",
      content: `Django>=4.2,<5.0\ndjangorestframework>=3.14.0\npython-decouple>=3.8${opts.has("postgres") ? `\npsycopg2-binary>=2.9` : ""}${opts.has("celery") ? `\ncelery>=5.3\nredis>=5.0` : ""}\n`,
    },
    {
      path: "manage.py",
      content: `#!/usr/bin/env python\nimport os\nimport sys\ndef main():\n    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")\n    from django.core.management import execute_from_command_line\n    execute_from_command_line(sys.argv)\nif __name__ == "__main__":\n    main()\n`,
    },
    {
      path: "config/settings.py",
      content: `from decouple import config\nSECRET_KEY = config("SECRET_KEY", default="change-me")\nDEBUG = config("DEBUG", default=True, cast=bool)\nALLOWED_HOSTS = ["*"]\nINSTALLED_APPS = [\n    "django.contrib.admin", "django.contrib.auth", "django.contrib.contenttypes",\n    "django.contrib.sessions", "django.contrib.messages", "django.contrib.staticfiles",\n    "rest_framework",\n]\nDATABASES = { "default": {${opts.has("postgres") ? `\n    "ENGINE": "django.db.backends.postgresql",\n    "NAME": config("DB_NAME", default="app"),\n    "USER": config("DB_USER", default="postgres"),\n    "PASSWORD": config("DB_PASSWORD", default="postgres"),\n    "HOST": config("DB_HOST", default="localhost"),\n    "PORT": "5432",` : `\n    "ENGINE": "django.db.backends.sqlite3",\n    "NAME": "db.sqlite3",`}\n}}\nSTATIC_URL = "/static/"\nDEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"\n`,
    },
    { path: ".env.example", content: `SECRET_KEY=your-secret-key-here\nDEBUG=True${opts.has("postgres") ? `\nDB_NAME=app\nDB_USER=postgres\nDB_PASSWORD=postgres\nDB_HOST=localhost` : ""}\n` },
  ];

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]\n` });
  }

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: Django CI\non:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.12"\n      - run: pip install -r requirements.txt\n      - run: python manage.py test\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\npython -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt\ncp .env.example .env\npython manage.py migrate\npython manage.py runserver\n\`\`\`\n` });
  return toYaml(files);
}

function buildRailsYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "Gemfile",
      content: `source "https://rubygems.org"\nruby "3.3.0"\ngem "rails", "~> 7.1.0"\ngem "puma", ">= 5.0"${opts.has("postgres") ? `\ngem "pg", ">= 0.18"` : `\ngem "sqlite3", ">= 1.4"`}${opts.has("redis") ? `\ngem "redis", ">= 4.0.1"` : ""}${opts.has("devise") ? `\ngem "devise"` : ""}\ngroup :development, :test do\n  gem "debug"\n  gem "rspec-rails"\nend\n`,
    },
    {
      path: "config/database.yml",
      content: `default: &default\n  adapter: ${opts.has("postgres") ? "postgresql" : "sqlite3"}\n  pool: 5\ndevelopment:\n  <<: *default\n  database: {{projectName}}_development\ntest:\n  <<: *default\n  database: {{projectName}}_test\nproduction:\n  <<: *default\n  url: <%= ENV["DATABASE_URL"] %>\n`,
    },
  ];

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM ruby:3.3-alpine\nRUN apk add --no-cache build-base nodejs yarn${opts.has("postgres") ? " postgresql-dev" : ""}\nWORKDIR /app\nCOPY Gemfile Gemfile.lock ./\nRUN bundle install\nCOPY . .\nEXPOSE 3000\nCMD ["rails", "server", "-b", "0.0.0.0"]\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\nbundle install\nrails db:create db:migrate\nrails server\n\`\`\`\n` });
  return toYaml(files);
}

// ── MOBILE ────────────────────────────────────────────────────────────────────

function buildExpoYaml(opts: Set<string>): string {
  const ts = opts.has("typescript");
  const ext = ts ? "tsx" : "jsx";
  const files: { path: string; content: string }[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": { "start": "expo start", "android": "expo start --android", "ios": "expo start --ios" },
  "dependencies": {
    "expo": "~50.0.0",
    "expo-router": "~3.4.0",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"${ts ? `,\n    "typescript": "^5",\n    "@types/react": "~18.2.45"` : ""}
  }
}
`,
    },
    {
      path: `app/(tabs)/index.${ext}`,
      content: `import { View, Text, StyleSheet } from "react-native";\nexport default function HomeScreen() {\n  return (\n    <View style={styles.container}>\n      <Text style={styles.title}>Welcome to {{projectName}}</Text>\n    </View>\n  );\n}\nconst styles = StyleSheet.create({\n  container: { flex: 1, alignItems: "center", justifyContent: "center" },\n  title: { fontSize: 24, fontWeight: "bold" },\n});\n`,
    },
    { path: "app.json", content: `{\n  "expo": {\n    "name": "{{projectName}}",\n    "slug": "{{projectName}}",\n    "version": "1.0.0",\n    "orientation": "portrait",\n    "scheme": "myapp",\n    "platforms": ["ios", "android", "web"]\n  }\n}\n` },
  ];

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: Expo CI\non:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: "20"\n          cache: "npm"\n      - run: npm ci\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpx expo start\n\`\`\`\n` });
  return toYaml(files);
}

function buildFlutterYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "pubspec.yaml",
      content: `name: {{projectName}}\ndescription: Generated by DevCentral Scaffolder\nversion: 1.0.0+1\npublish_to: "none"\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\ndependencies:\n  flutter:\n    sdk: flutter\n  cupertino_icons: ^1.0.6${opts.has("firebase") ? `\n  firebase_core: ^2.24.0\n  firebase_auth: ^4.15.0` : ""}\ndev_dependencies:\n  flutter_test:\n    sdk: flutter\n  flutter_lints: ^3.0.0\nflutter:\n  uses-material-design: true\n`,
    },
    {
      path: "lib/main.dart",
      content: `import "package:flutter/material.dart";\nvoid main() { runApp(const MyApp()); }\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(\n      title: "{{projectName}}",\n      theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple), useMaterial3: true),\n      home: const HomeScreen(),\n    );\n  }\n}\nclass HomeScreen extends StatelessWidget {\n  const HomeScreen({super.key});\n  @override\n  Widget build(BuildContext context) {\n    return Scaffold(\n      appBar: AppBar(title: const Text("{{projectName}}")),\n      body: const Center(child: Text("Welcome to {{projectName}}!", style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold))),\n    );\n  }\n}\n`,
    },
  ];

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: Flutter CI\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: subosito/flutter-action@v2\n        with:\n          flutter-version: "3.x"\n      - run: flutter pub get\n      - run: flutter analyze\n      - run: flutter test\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\nflutter pub get\nflutter run\n\`\`\`\n` });
  return toYaml(files);
}

function buildSwiftIosYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "{{projectName}}/ContentView.swift",
      content: `import SwiftUI\nstruct ContentView: View {\n    var body: some View {\n        VStack {\n            Image(systemName: "globe").imageScale(.large).foregroundStyle(.tint)\n            Text("Welcome to {{projectName}}").font(.largeTitle).bold()\n        }.padding()\n    }\n}\n#Preview { ContentView() }\n`,
    },
    {
      path: "{{projectName}}/{{projectName}}App.swift",
      content: `import SwiftUI\n@main\nstruct {{projectName}}App: App {\n    var body: some Scene {\n        WindowGroup { ContentView() }\n    }\n}\n`,
    },
    { path: "Package.swift", content: `// swift-tools-version: 5.9\nimport PackageDescription\nlet package = Package(\n    name: "{{projectName}}",\n    platforms: [.iOS(.v17)],\n    products: [.library(name: "{{projectName}}", targets: ["{{projectName}}"])],\n    dependencies: [],\n    targets: [.target(name: "{{projectName}}"), .testTarget(name: "{{projectName}}Tests", dependencies: ["{{projectName}}"])]\n)\n` },
  ];

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: Swift iOS CI\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: macos-14\n    steps:\n      - uses: actions/checkout@v4\n      - name: Build\n        run: xcodebuild -scheme {{projectName}} -destination "platform=iOS Simulator,name=iPhone 15" build\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\nOpen in Xcode and run on a simulator or device.\n` });
  return toYaml(files);
}

function buildKotlinAndroidYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "app/build.gradle.kts",
      content: `plugins {\n    id("com.android.application")\n    id("org.jetbrains.kotlin.android")\n}\nandroid {\n    namespace = "com.{{projectName}}"\n    compileSdk = 34\n    defaultConfig {\n        applicationId = "com.{{projectName}}"\n        minSdk = 26\n        targetSdk = 34\n        versionCode = 1\n        versionName = "1.0"\n    }\n    buildFeatures { compose = true }\n    composeOptions { kotlinCompilerExtensionVersion = "1.5.8" }\n}\ndependencies {\n    implementation("androidx.core:core-ktx:1.12.0")\n    implementation("androidx.activity:activity-compose:1.8.2")\n    implementation(platform("androidx.compose:compose-bom:2024.02.00"))\n    implementation("androidx.compose.ui:ui")\n    implementation("androidx.compose.material3:material3")${opts.has("firebase") ? `\n    implementation(platform("com.google.firebase:firebase-bom:32.7.0"))\n    implementation("com.google.firebase:firebase-auth-ktx")` : ""}\n}\n`,
    },
    {
      path: "app/src/main/java/com/{{projectName}}/MainActivity.kt",
      content: `package com.{{projectName}}\nimport android.os.Bundle\nimport androidx.activity.ComponentActivity\nimport androidx.activity.compose.setContent\nimport androidx.compose.foundation.layout.*\nimport androidx.compose.material3.*\nimport androidx.compose.ui.Alignment\nimport androidx.compose.ui.Modifier\nclass MainActivity : ComponentActivity() {\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContent {\n            MaterialTheme {\n                Surface(modifier = Modifier.fillMaxSize()) {\n                    Box(contentAlignment = Alignment.Center) {\n                        Text(text = "Welcome to {{projectName}}", style = MaterialTheme.typography.headlineLarge)\n                    }\n                }\n            }\n        }\n    }\n}\n`,
    },
  ];

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: Android CI\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-java@v4\n        with:\n          java-version: "17"\n          distribution: "temurin"\n      - run: ./gradlew assembleDebug\n      - run: ./gradlew test\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\nOpen in Android Studio and run on an emulator or device.\n` });
  return toYaml(files);
}

// ── BACKEND ───────────────────────────────────────────────────────────────────

function buildExpressYaml(opts: Set<string>): string {
  const ts = opts.has("typescript");
  const ext = ts ? "ts" : "js";
  const files: { path: string; content: string }[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "1.0.0",
  "main": "${ts ? "dist/index.js" : "src/index.js"}",
  "scripts": {
    "dev": "${ts ? "ts-node src/index.ts" : "node src/index.js"}",
    "build": "${ts ? "tsc" : "echo 'No build step'"}",
    "test": "jest"
  },
  "dependencies": {
    "express": "^4.19.2"${opts.has("prisma") ? `,\n    "@prisma/client": "^5.0.0"` : ""}${opts.has("jwt") ? `,\n    "jsonwebtoken": "^9.0.0",\n    "bcrypt": "^5.1.1"` : ""}
  }${ts ? `,\n  "devDependencies": {\n    "typescript": "^5", "ts-node": "^10",\n    "@types/express": "^4", "@types/node": "^20"\n  }` : ""}
}
`,
    },
    {
      path: `src/index.${ext}`,
      content: `import express from "express";\nconst app = express();\nconst PORT = process.env.PORT || 3000;\napp.use(express.json());\napp.get("/health", (_req, res) => { res.json({ status: "ok", service: "{{projectName}}" }); });\napp.listen(PORT, () => { console.log(\`Server running on port \${PORT}\`); });\nexport default app;\n`,
    },
    { path: ".env.example", content: `PORT=3000\nNODE_ENV=development${opts.has("prisma") ? `\nDATABASE_URL=postgresql://user:password@localhost:5432/{{projectName}}` : ""}${opts.has("jwt") ? `\nJWT_SECRET=your-secret-key-here` : ""}\n` },
  ];

  if (ts) {
    files.push({ path: "tsconfig.json", content: `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "commonjs",\n    "outDir": "./dist",\n    "rootDir": "./src",\n    "strict": true,\n    "esModuleInterop": true,\n    "skipLibCheck": true\n  },\n  "include": ["src/**/*"],\n  "exclude": ["node_modules", "dist"]\n}\n` });
  }

  if (opts.has("prisma")) {
    files.push({ path: "prisma/schema.prisma", content: `datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\ngenerator client {\n  provider = "prisma-client-js"\n}\nmodel User {\n  id        String   @id @default(cuid())\n  email     String   @unique\n  name      String?\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n` });
  }

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\nCOPY . .\nEXPOSE 3000\nCMD ["${ts ? "node dist/index.js" : "node src/index.js"}"]\n` });
  }

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: Express CI\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: "20"\n          cache: "npm"\n      - run: npm ci\n      - run: npm test\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Endpoints\n\n- \`GET /health\` — Health check\n` });
  return toYaml(files);
}

function buildNestJsYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.0.1",
  "scripts": {
    "build": "nest build",
    "start:dev": "nest start --watch",
    "start:prod": "node dist/main",
    "test": "jest"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"${opts.has("prisma") ? `,\n    "@prisma/client": "^5.0.0"` : ""}${opts.has("jwt") ? `,\n    "@nestjs/jwt": "^10.1.1",\n    "@nestjs/passport": "^10.0.0",\n    "passport": "^0.6.0",\n    "passport-jwt": "^4.0.1"` : ""}
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "typescript": "^5",
    "@types/node": "^20"
  }
}
`,
    },
    { path: "src/main.ts", content: `import { NestFactory } from "@nestjs/core";\nimport { AppModule } from "./app.module";\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule);\n  await app.listen(process.env.PORT || 3000);\n}\nbootstrap();\n` },
    { path: "src/app.module.ts", content: `import { Module } from "@nestjs/common";\nimport { AppController } from "./app.controller";\nimport { AppService } from "./app.service";\n@Module({ imports: [], controllers: [AppController], providers: [AppService] })\nexport class AppModule {}\n` },
    { path: "src/app.controller.ts", content: `import { Controller, Get } from "@nestjs/common";\nimport { AppService } from "./app.service";\n@Controller()\nexport class AppController {\n  constructor(private readonly appService: AppService) {}\n  @Get() getHello(): string { return this.appService.getHello(); }\n  @Get("health") getHealth() { return { status: "ok", service: "{{projectName}}" }; }\n}\n` },
    { path: "src/app.service.ts", content: `import { Injectable } from "@nestjs/common";\n@Injectable()\nexport class AppService {\n  getHello(): string { return "Welcome to {{projectName}}!"; }\n}\n` },
    { path: "tsconfig.json", content: `{\n  "compilerOptions": {\n    "module": "commonjs",\n    "declaration": true,\n    "emitDecoratorMetadata": true,\n    "experimentalDecorators": true,\n    "allowSyntheticDefaultImports": true,\n    "target": "ES2021",\n    "sourceMap": true,\n    "outDir": "./dist",\n    "baseUrl": "./",\n    "skipLibCheck": true\n  }\n}\n` },
  ];

  if (opts.has("prisma")) {
    files.push({ path: "prisma/schema.prisma", content: `datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\ngenerator client {\n  provider = "prisma-client-js"\n}\nmodel User {\n  id        String   @id @default(cuid())\n  email     String   @unique\n  name      String?\n  createdAt DateTime @default(now())\n}\n` });
  }

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\nFROM node:20-alpine AS runner\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY --from=builder /app/node_modules ./node_modules\nEXPOSE 3000\nCMD ["node", "dist/main"]\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run start:dev\n\`\`\`\n` });
  return toYaml(files);
}

function buildFastApiYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "requirements.txt",
      content: `fastapi>=0.109.0\nuvicorn[standard]>=0.27.0\npydantic>=2.5.0${opts.has("postgres") ? `\nasyncpg>=0.29.0\nsqlalchemy[asyncio]>=2.0.0` : ""}${opts.has("jwt") ? `\npython-jose[cryptography]>=3.3.0\npasslib[bcrypt]>=1.7.4` : ""}${opts.has("celery") ? `\ncelery>=5.3.0\nredis>=5.0.0` : ""}\n`,
    },
    {
      path: "app/main.py",
      content: `from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\napp = FastAPI(title="{{projectName}}", version="0.1.0")\napp.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])\n@app.get("/health")\nasync def health_check():\n    return {"status": "ok", "service": "{{projectName}}"}\n@app.get("/")\nasync def root():\n    return {"message": "Welcome to {{projectName}}"}\n`,
    },
    { path: ".env.example", content: `APP_ENV=development${opts.has("postgres") ? `\nDATABASE_URL=postgresql+asyncpg://user:password@localhost:5432/{{projectName}}` : ""}${opts.has("jwt") ? `\nSECRET_KEY=your-secret-key-here\nALGORITHM=HS256` : ""}\n` },
  ];

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]\n` });
  }

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: FastAPI CI\non:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.12"\n      - run: pip install -r requirements.txt pytest httpx\n      - run: pytest\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\npython -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt\nuvicorn app.main:app --reload\n\`\`\`\n\nDocs: http://localhost:8000/docs\n` });
  return toYaml(files);
}

function buildGoGinYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "go.mod",
      content: `module github.com/{{projectName}}\ngo 1.22\nrequire (\n\tgithub.com/gin-gonic/gin v1.9.1${opts.has("gorm") ? `\n\tgorm.io/gorm v1.25.7\n\tgorm.io/driver/postgres v1.5.6` : ""}${opts.has("jwt") ? `\n\tgithub.com/golang-jwt/jwt/v5 v5.2.0` : ""}\n)\n`,
    },
    {
      path: "main.go",
      content: `package main\nimport (\n\t"net/http"\n\t"github.com/gin-gonic/gin"\n)\nfunc main() {\n\tr := gin.Default()\n\tr.GET("/health", func(c *gin.Context) {\n\t\tc.JSON(http.StatusOK, gin.H{"status": "ok", "service": "{{projectName}}"})\n\t})\n\tr.GET("/", func(c *gin.Context) {\n\t\tc.JSON(http.StatusOK, gin.H{"message": "Welcome to {{projectName}}"})\n\t})\n\tr.Run(":8080")\n}\n`,
    },
    { path: ".env.example", content: `PORT=8080\nGIN_MODE=debug${opts.has("gorm") ? `\nDATABASE_URL=postgresql://user:password@localhost:5432/{{projectName}}?sslmode=disable` : ""}${opts.has("jwt") ? `\nJWT_SECRET=your-secret-key-here` : ""}\n` },
  ];

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM golang:1.22-alpine AS builder\nWORKDIR /app\nCOPY go.mod go.sum ./\nRUN go mod download\nCOPY . .\nRUN CGO_ENABLED=0 GOOS=linux go build -o main .\nFROM alpine:3.19\nWORKDIR /app\nCOPY --from=builder /app/main .\nEXPOSE 8080\nCMD ["./main"]\n` });
  }

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: Go Gin CI\non:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-go@v5\n        with:\n          go-version: "1.22"\n      - run: go mod download\n      - run: go build ./...\n      - run: go test ./...\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\ngo mod tidy\ngo run main.go\n\`\`\`\n` });
  return toYaml(files);
}

function buildSpringBootYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "pom.xml",
      content: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.2</version>
  </parent>
  <groupId>com.{{projectName}}</groupId>
  <artifactId>{{projectName}}</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties><java.version>21</java.version></properties>
  <dependencies>
    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency>${opts.has("jpa") ? `\n    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency>` : ""}${opts.has("postgres") ? `\n    <dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId></dependency>` : ""}${opts.has("security") ? `\n    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-security</artifactId></dependency>` : ""}
    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency>
  </dependencies>
  <build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build>
</project>
`,
    },
    { path: "src/main/java/com/{{projectName}}/Application.java", content: `package com.{{projectName}};\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n@SpringBootApplication\npublic class Application {\n    public static void main(String[] args) { SpringApplication.run(Application.class, args); }\n}\n` },
    { path: "src/main/java/com/{{projectName}}/HealthController.java", content: `package com.{{projectName}};\nimport org.springframework.web.bind.annotation.*;\nimport java.util.Map;\n@RestController\npublic class HealthController {\n    @GetMapping("/health")\n    public Map<String, String> health() { return Map.of("status", "ok", "service", "{{projectName}}"); }\n}\n` },
    { path: "src/main/resources/application.properties", content: `server.port=8080\nspring.application.name={{projectName}}${opts.has("postgres") ? `\nspring.datasource.url=jdbc:postgresql://localhost:5432/{{projectName}}\nspring.datasource.username=postgres\nspring.datasource.password=postgres\nspring.jpa.hibernate.ddl-auto=update` : ""}\n` },
  ];

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM eclipse-temurin:21-jdk AS builder\nWORKDIR /app\nCOPY . .\nRUN ./mvnw clean package -DskipTests\nFROM eclipse-temurin:21-jre\nWORKDIR /app\nCOPY --from=builder /app/target/*.jar app.jar\nEXPOSE 8080\nENTRYPOINT ["java", "-jar", "app.jar"]\n` });
  }

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: Spring Boot CI\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-java@v4\n        with:\n          java-version: "21"\n          distribution: "temurin"\n      - run: ./mvnw clean verify\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\n./mvnw spring-boot:run\n\`\`\`\n` });
  return toYaml(files);
}

// ── DATA & AI ─────────────────────────────────────────────────────────────────

function buildPyTorchYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "requirements.txt",
      content: `torch>=2.2.0\ntorchvision>=0.17.0\nnumpy>=1.26.0\nmatplotlib>=3.8.0\ntqdm>=4.66.0${opts.has("mlflow") ? `\nmlflow>=2.10.0` : ""}${opts.has("wandb") ? `\nwandb>=0.16.0` : ""}\n`,
    },
    {
      path: "src/model.py",
      content: `import torch\nimport torch.nn as nn\nclass {{projectName}}Model(nn.Module):\n    def __init__(self, input_size: int, hidden_size: int, output_size: int):\n        super().__init__()\n        self.network = nn.Sequential(\n            nn.Linear(input_size, hidden_size), nn.ReLU(), nn.Dropout(0.2),\n            nn.Linear(hidden_size, hidden_size), nn.ReLU(),\n            nn.Linear(hidden_size, output_size),\n        )\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.network(x)\n`,
    },
    {
      path: "src/train.py",
      content: `import torch\nimport torch.nn as nn\nfrom model import {{projectName}}Model\nDEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")\nEPOCHS = 10\nLR = 1e-3\ndef train():\n    model = {{projectName}}Model(input_size=784, hidden_size=256, output_size=10).to(DEVICE)\n    optimizer = torch.optim.Adam(model.parameters(), lr=LR)\n    print(f"Training on {DEVICE} | Parameters: {sum(p.numel() for p in model.parameters()):,}")\n    for epoch in range(EPOCHS):\n        print(f"Epoch {epoch + 1}/{EPOCHS}")\n    torch.save(model.state_dict(), "model.pth")\n    print("Model saved to model.pth")\nif __name__ == "__main__":\n    train()\n`,
    },
  ];

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD ["python", "src/train.py"]\n` });
  }

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: PyTorch CI\non:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.12"\n      - run: pip install -r requirements.txt pytest\n      - run: pytest tests/ -v\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\npython -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt\npython src/train.py\n\`\`\`\n` });
  return toYaml(files);
}

function buildLangChainYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "requirements.txt",
      content: `langchain>=0.1.0\nlangchain-openai>=0.0.5\nlangchain-community>=0.0.20\npython-dotenv>=1.0.0${opts.has("chroma") ? `\nchromadb>=0.4.22` : ""}${opts.has("streamlit") ? `\nstreamlit>=1.31.0` : ""}\n`,
    },
    {
      path: "src/chain.py",
      content: `from langchain_openai import ChatOpenAI\nfrom langchain.prompts import ChatPromptTemplate\nfrom langchain.schema.output_parser import StrOutputParser\ndef build_chain():\n    llm = ChatOpenAI(model="gpt-4-turbo-preview", temperature=0)\n    prompt = ChatPromptTemplate.from_messages([\n        ("system", "You are a helpful AI assistant for {{projectName}}."),\n        ("human", "{question}"),\n    ])\n    return prompt | llm | StrOutputParser()\nif __name__ == "__main__":\n    chain = build_chain()\n    result = chain.invoke({"question": "What can you help me with?"})\n    print(result)\n`,
    },
    { path: ".env.example", content: `OPENAI_API_KEY=sk-your-key-here\nLANGCHAIN_API_KEY=ls-your-key-here\nLANGCHAIN_TRACING_V2=true\nLANGCHAIN_PROJECT={{projectName}}\n` },
  ];

  if (opts.has("streamlit")) {
    files.push({
      path: "app.py",
      content: `import streamlit as st\nfrom dotenv import load_dotenv\nfrom src.chain import build_chain\nload_dotenv()\nst.title("{{projectName}}")\nst.caption("Powered by LangChain + OpenAI")\nif "messages" not in st.session_state:\n    st.session_state.messages = []\nchain = build_chain()\nfor message in st.session_state.messages:\n    with st.chat_message(message["role"]):\n        st.markdown(message["content"])\nif prompt := st.chat_input("Ask a question..."):\n    st.session_state.messages.append({"role": "user", "content": prompt})\n    with st.chat_message("user"): st.markdown(prompt)\n    with st.chat_message("assistant"):\n        response = chain.invoke({"question": prompt})\n        st.markdown(response)\n    st.session_state.messages.append({"role": "assistant", "content": response})\n`,
    });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\npython -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt\ncp .env.example .env\n# Add your OPENAI_API_KEY to .env\npython src/chain.py\n\`\`\`\n` });
  return toYaml(files);
}

function buildDataPipelineYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "requirements.txt",
      content: `pandas>=2.2.0\npyarrow>=15.0.0\ndask>=2024.2.0${opts.has("airflow") ? `\napache-airflow>=2.8.0` : ""}${opts.has("postgres") ? `\npsycopg2-binary>=2.9.0\nsqlalchemy>=2.0.0` : ""}\ngreat-expectations>=0.18.0\n`,
    },
    {
      path: "src/pipeline.py",
      content: `import pandas as pd\nfrom pathlib import Path\ndef extract(source_path: str) -> pd.DataFrame:\n    path = Path(source_path)\n    if path.suffix == ".csv": return pd.read_csv(path)\n    elif path.suffix == ".parquet": return pd.read_parquet(path)\n    raise ValueError(f"Unsupported format: {path.suffix}")\ndef transform(df: pd.DataFrame) -> pd.DataFrame:\n    df = df.dropna()\n    df.columns = [col.lower().strip().replace(" ", "_") for col in df.columns]\n    return df\ndef load(df: pd.DataFrame, dest_path: str) -> None:\n    path = Path(dest_path)\n    path.parent.mkdir(parents=True, exist_ok=True)\n    df.to_parquet(path, index=False)\n    print(f"Loaded {len(df):,} rows to {dest_path}")\ndef run(source: str, dest: str) -> None:\n    df = extract(source)\n    df = transform(df)\n    load(df, dest)\n    print("Pipeline complete.")\nif __name__ == "__main__":\n    run("data/input/sample.csv", "data/output/processed.parquet")\n`,
    },
    { path: "data/input/.gitkeep", content: "" },
    { path: "data/output/.gitkeep", content: "" },
  ];

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD ["python", "src/pipeline.py"]\n` });
  }

  if (opts.has("ci")) {
    files.push({ path: ".github/workflows/ci.yml", content: `name: Data Pipeline CI\non:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.12"\n      - run: pip install -r requirements.txt pytest\n      - run: pytest tests/\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\npython -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt\npython src/pipeline.py\n\`\`\`\n` });
  return toYaml(files);
}

function buildJupyterYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "requirements.txt",
      content: `jupyter>=1.0.0\njupyterlab>=4.1.0\npandas>=2.2.0\nnumpy>=1.26.0\nmatplotlib>=3.8.0\nseaborn>=0.13.0\nscikit-learn>=1.4.0${opts.has("plotly") ? `\nplotly>=5.19.0\nipywidgets>=8.1.0` : ""}\n`,
    },
    {
      path: "src/utils.py",
      content: `"""Utility functions for {{projectName}}."""\nimport pandas as pd\ndef describe_dataframe(df: pd.DataFrame) -> None:\n    print(f"Shape: {df.shape}")\n    print(f"Memory: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")\n    print(f"\\nDtypes:\\n{df.dtypes}")\n    print(f"\\nNull counts:\\n{df.isnull().sum()}")\n`,
    },
    { path: "data/.gitkeep", content: "" },
  ];

  if (opts.has("docker")) {
    files.push({ path: "Dockerfile", content: `FROM jupyter/datascience-notebook:python-3.12\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8888\nCMD ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--allow-root"]\n` });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\npython -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt\njupyter lab\n\`\`\`\n` });
  return toYaml(files);
}

// ── DEVOPS ────────────────────────────────────────────────────────────────────

function buildDockerComposeYaml(opts: Set<string>): string {
  let services = `services:\n  app:\n    build: .\n    ports:\n      - "3000:3000"\n    env_file: .env\n    depends_on:`;
  if (opts.has("postgres")) services += `\n      db:\n        condition: service_healthy`;
  if (opts.has("redis")) services += `\n      redis:\n        condition: service_started`;
  services += `\n    networks:\n      - app-network`;

  if (opts.has("postgres")) {
    services += `\n\n  db:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: \${DB_NAME:-app}\n      POSTGRES_USER: \${DB_USER:-postgres}\n      POSTGRES_PASSWORD: \${DB_PASSWORD:-postgres}\n    volumes:\n      - postgres-data:/var/lib/postgresql/data\n    ports:\n      - "5432:5432"\n    healthcheck:\n      test: ["CMD-SHELL", "pg_isready -U \${DB_USER:-postgres}"]\n      interval: 10s\n      retries: 5\n    networks:\n      - app-network`;
  }
  if (opts.has("redis")) {
    services += `\n\n  redis:\n    image: redis:7-alpine\n    ports:\n      - "6379:6379"\n    volumes:\n      - redis-data:/data\n    networks:\n      - app-network`;
  }

  services += `\n\nvolumes:${opts.has("postgres") ? `\n  postgres-data:` : ""}${opts.has("redis") ? `\n  redis-data:` : ""}\n\nnetworks:\n  app-network:\n    driver: bridge`;

  const files = [
    { path: "docker-compose.yml", content: services },
    { path: "Dockerfile", content: `FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nEXPOSE 3000\nCMD ["node", "src/index.js"]\n` },
    { path: ".env.example", content: `NODE_ENV=development\nPORT=3000${opts.has("postgres") ? `\nDB_NAME=app\nDB_USER=postgres\nDB_PASSWORD=postgres\nDB_HOST=db` : ""}${opts.has("redis") ? `\nREDIS_URL=redis://redis:6379` : ""}\n` },
    { path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\ncp .env.example .env\ndocker compose up -d\ndocker compose logs -f app\n\`\`\`\n` },
  ];

  return toYaml(files);
}

function buildGithubActionsYaml(): string {
  const files: { path: string; content: string }[] = [
    {
      path: ".github/workflows/ci.yml",
      content: `name: CI\non:\n  push:\n    branches: [main, develop]\n  pull_request:\n    branches: [main]\njobs:\n  lint:\n    name: Lint\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: "20"\n          cache: "npm"\n      - run: npm ci\n      - run: npm run lint\n  test:\n    name: Test\n    runs-on: ubuntu-latest\n    needs: lint\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: "20"\n          cache: "npm"\n      - run: npm ci\n      - run: npm test -- --coverage\n`,
    },
    {
      path: ".github/workflows/cd.yml",
      content: `name: CD\non:\n  push:\n    tags:\n      - "v*.*.*"\njobs:\n  deploy:\n    name: Deploy\n    runs-on: ubuntu-latest\n    environment: production\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: "20"\n          cache: "npm"\n      - run: npm ci\n      - run: npm run build\n`,
    },
    {
      path: ".github/workflows/security.yml",
      content: `name: Security\non:\n  schedule:\n    - cron: "0 8 * * 1"\n  push:\n    branches: [main]\njobs:\n  audit:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: "20"\n      - run: npm audit --audit-level=moderate\n  codeql:\n    runs-on: ubuntu-latest\n    permissions:\n      security-events: write\n    steps:\n      - uses: actions/checkout@v4\n      - uses: github/codeql-action/init@v3\n        with:\n          languages: javascript\n      - uses: github/codeql-action/analyze@v3\n`,
    },
    { path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## CI/CD\n\n- **CI**: Runs lint + tests on every push\n- **CD**: Deploys on version tags (\`v*.*.*\`)\n- **Security**: Weekly dependency audits + CodeQL\n` },
  ];

  return toYaml(files);
}

function buildTerraformAwsYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    {
      path: "main.tf",
      content: `terraform {\n  required_version = ">= 1.7.0"\n  required_providers {\n    aws = { source = "hashicorp/aws", version = "~> 5.0" }\n  }\n}\nprovider "aws" {\n  region = var.aws_region\n  default_tags {\n    tags = {\n      Project     = "{{projectName}}"\n      ManagedBy   = "Terraform"\n      Environment = var.environment\n    }\n  }\n}\n`,
    },
    {
      path: "variables.tf",
      content: `variable "aws_region" {\n  description = "AWS region"\n  type        = string\n  default     = "us-east-1"\n}\nvariable "environment" {\n  description = "Deployment environment"\n  type        = string\n  default     = "production"\n}\nvariable "app_name" {\n  description = "Application name"\n  type        = string\n  default     = "{{projectName}}"\n}\n`,
    },
    { path: "outputs.tf", content: `output "region" {\n  description = "AWS region"\n  value       = var.aws_region\n}\n` },
    { path: ".gitignore", content: `.terraform/\n*.tfstate\n*.tfstate.*\n*.tfvars\n!terraform.tfvars.example\n.terraform.lock.hcl\n` },
    { path: "terraform.tfvars.example", content: `aws_region  = "us-east-1"\nenvironment = "production"\napp_name    = "{{projectName}}"\n` },
  ];

  if (opts.has("ci")) {
    files.push({
      path: ".github/workflows/terraform.yml",
      content: `name: Terraform\non:\n  pull_request:\n    branches: [main]\n  push:\n    branches: [main]\njobs:\n  terraform:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: hashicorp/setup-terraform@v3\n        with:\n          terraform_version: "1.7.0"\n      - name: Configure AWS credentials\n        uses: aws-actions/configure-aws-credentials@v4\n        with:\n          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}\n          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}\n          aws-region: us-east-1\n      - run: terraform init\n      - run: terraform fmt -check\n      - run: terraform validate\n      - run: terraform plan -no-color\n`,
    });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Getting Started\n\n\`\`\`bash\ncp terraform.tfvars.example terraform.tfvars\nterraform init\nterraform plan\nterraform apply\n\`\`\`\n` });
  return toYaml(files);
}

function buildKubernetesYaml(opts: Set<string>): string {
  const files: { path: string; content: string }[] = [
    { path: "k8s/namespace.yaml", content: `apiVersion: v1\nkind: Namespace\nmetadata:\n  name: {{projectName}}\n  labels:\n    app.kubernetes.io/managed-by: kubectl\n` },
    {
      path: "k8s/deployment.yaml",
      content: `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{projectName}}\n  namespace: {{projectName}}\n  labels:\n    app: {{projectName}}\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: {{projectName}}\n  template:\n    metadata:\n      labels:\n        app: {{projectName}}\n    spec:\n      containers:\n        - name: {{projectName}}\n          image: your-registry/{{projectName}}:latest\n          ports:\n            - containerPort: 3000\n          resources:\n            requests:\n              cpu: "100m"\n              memory: "128Mi"\n            limits:\n              cpu: "500m"\n              memory: "512Mi"\n          livenessProbe:\n            httpGet:\n              path: /health\n              port: 3000\n            initialDelaySeconds: 15\n            periodSeconds: 20\n`,
    },
    { path: "k8s/service.yaml", content: `apiVersion: v1\nkind: Service\nmetadata:\n  name: {{projectName}}\n  namespace: {{projectName}}\nspec:\n  selector:\n    app: {{projectName}}\n  ports:\n    - protocol: TCP\n      port: 80\n      targetPort: 3000\n  type: ClusterIP\n` },
    { path: "k8s/configmap.yaml", content: `apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: {{projectName}}-config\n  namespace: {{projectName}}\ndata:\n  NODE_ENV: "production"\n  PORT: "3000"\n` },
    { path: "k8s/secret.example.yaml", content: `# Copy to secret.yaml and fill in base64 encoded values\napiVersion: v1\nkind: Secret\nmetadata:\n  name: {{projectName}}-secrets\n  namespace: {{projectName}}\ntype: Opaque\ndata:\n  DATABASE_URL: <base64-encoded-value>\n` },
  ];

  if (opts.has("ingress")) {
    files.push({
      path: "k8s/ingress.yaml",
      content: `apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: {{projectName}}\n  namespace: {{projectName}}\n  annotations:\n    nginx.ingress.kubernetes.io/rewrite-target: /\n    cert-manager.io/cluster-issuer: letsencrypt-prod\nspec:\n  ingressClassName: nginx\n  tls:\n    - hosts:\n        - {{projectName}}.example.com\n      secretName: {{projectName}}-tls\n  rules:\n    - host: {{projectName}}.example.com\n      http:\n        paths:\n          - path: /\n            pathType: Prefix\n            backend:\n              service:\n                name: {{projectName}}\n                port:\n                  number: 80\n`,
    });
  }

  if (opts.has("hpa")) {
    files.push({
      path: "k8s/hpa.yaml",
      content: `apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: {{projectName}}\n  namespace: {{projectName}}\nspec:\n  scaleTargetRef:\n    apiVersion: apps/v1\n    kind: Deployment\n    name: {{projectName}}\n  minReplicas: 2\n  maxReplicas: 10\n  metrics:\n    - type: Resource\n      resource:\n        name: cpu\n        target:\n          type: Utilization\n          averageUtilization: 70\n`,
    });
  }

  if (opts.has("ci")) {
    files.push({
      path: ".github/workflows/deploy.yml",
      content: `name: Deploy to Kubernetes\non:\n  push:\n    tags:\n      - "v*.*.*"\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Configure kubectl\n        uses: azure/k8s-set-context@v4\n        with:\n          method: kubeconfig\n          kubeconfig: \${{ secrets.KUBE_CONFIG }}\n      - name: Deploy\n        run: |\n          kubectl set image deployment/{{projectName}} \\\n            {{projectName}}=your-registry/{{projectName}}:\${{ github.ref_name }} \\\n            -n {{projectName}}\n          kubectl rollout status deployment/{{projectName}} -n {{projectName}}\n`,
    });
  }

  files.push({ path: "README.md", content: `# {{projectName}}\n\nGenerated by DevCentral Scaffolder.\n\n## Deploy to Kubernetes\n\n\`\`\`bash\nkubectl apply -f k8s/namespace.yaml\nkubectl apply -f k8s/configmap.yaml\n# Create secret.yaml from secret.example.yaml first\nkubectl apply -f k8s/deployment.yaml\nkubectl apply -f k8s/service.yaml\n\`\`\`\n` });
  return toYaml(files);
}

// ── Dispatch ──────────────────────────────────────────────────────────────────

export function generateYaml(frameworkId: string, optionIds: string[]): string {
  const opts = new Set(optionIds);
  switch (frameworkId) {
    case "nextjs":           return buildNextjsYaml(opts);
    case "react-vite":       return buildReactViteYaml(opts);
    case "vue-nuxt":         return buildVueNuxtYaml(opts);
    case "sveltekit":        return buildSvelteKitYaml(opts);
    case "laravel":          return buildLaravelYaml(opts);
    case "django":           return buildDjangoYaml(opts);
    case "rails":            return buildRailsYaml(opts);
    case "expo":             return buildExpoYaml(opts);
    case "flutter":          return buildFlutterYaml(opts);
    case "swift-ios":        return buildSwiftIosYaml(opts);
    case "kotlin-android":   return buildKotlinAndroidYaml(opts);
    case "express":          return buildExpressYaml(opts);
    case "nestjs":           return buildNestJsYaml(opts);
    case "fastapi":          return buildFastApiYaml(opts);
    case "go-gin":           return buildGoGinYaml(opts);
    case "spring-boot":      return buildSpringBootYaml(opts);
    case "pytorch":          return buildPyTorchYaml(opts);
    case "langchain":        return buildLangChainYaml(opts);
    case "data-pipeline":    return buildDataPipelineYaml(opts);
    case "jupyter":          return buildJupyterYaml(opts);
    case "docker-compose":   return buildDockerComposeYaml(opts);
    case "github-actions":   return buildGithubActionsYaml();
    case "terraform-aws":    return buildTerraformAwsYaml(opts);
    case "kubernetes":       return buildKubernetesYaml(opts);
    default:
      return toYaml([{ path: "README.md", content: `# {{projectName}}\n\nFramework "${frameworkId}" is not yet supported.\n` }]);
  }
}
